devel/hb.php

Added a simple filtering form to the highway browser page.

Added basic system and region filters to hb.php

---

hbtest/chmviewerfunc3.js
lib/tmjsfuncs.js

Added Mapnik and MQOpen tiles to HB and mapview.php

---

devel/hb.php

Adds active/preview/devel highlighting to rows in the highway browser. (Green - active, Yellow - preview, Red - in development)

Added system-status highlighting to hb.php

---

user/chmviewerfunc3.js

Can we not have the same js file located in three different places?

Fix blank tile option not showing up in systems.php

---

devel/hb.php
hbtest/mapview.php
index.php
lib/tmjsfuncs.js
login.php
shields/clinched.php
stat.php
user/index.php
user/region.php
user/system.php

Web interface changes to use consolidated database with active-only and active+preview in a single DB.

Database consolidation

---

devel/datacheck.php
devel/updates.php
lib/tmfooter.php
lib/tmheader.php
lib/tmphpfuncs.php

Introduced new file lib/tmphpfuncs.php that connects to the DB and parses some QS parameters.  Updated devel php code to use this.  Others will follow.  All code in devel directory now passes XHTML 1.0 Strict validation.

Some refactoring and HTML validation.

---

lib/tmphpfuncs.php
lib/tmphpuser.php
user/index.php

User now selectable from dropdown menu.

Improvements to overall user stats page.

---

credits.php

Fixes dead links in Northwest Territories credits/sources list

Northwest Territories updates

---

credits.php

Updates credits/sources entries for BC and SK. Also minor edit to item in General Map References.
Updates to AK, CA, HI to follow in later pull request.

Remaining Canada credits updates

---

credits.php

Updates to credits lists for AK, CA, HI, NM. One resource I used for both CA and NM, which also covers other states, added to general sources for U.S.
This should complete my credits/sources updates.

Updates to credits lists for my U.S. jurisdictions

---

hb/index.php

Fixed bug accidentally introduced in #85.

Fixed #88.

---

hb/index.php
lib/tmphpuser.php
user/system.php

Fixes for problems introduced in #96, as well as #98.

Hotfixes for #96

---

lib/tmjsfuncs.js

changing it from gray to something more pink

change unclinched "lightsalmon" color

---

hb/index.php

Make whole table row clickable in HB's route waypoint table

---

css/travelMapping.css

Fun with browser specific rules!

Fix for the fix for the fix

---

shields/shieldgen.php
shields/template_hunf.svg
shields/template_hunm.svg
shields/template_luxa.svg
shields/template_luxa_wide.svg
shields/template_luxb.svg
shields/template_luxb_wide.svg
shields/template_luxn.svg
shields/template_luxn_wide.svg

Shields: HUN/LUX

---

credits.php

update credits with WY

---

credits.php

Added a few PA resources that I have consistently been using and added myself to the contributors list.  -Mark

Adding PA References to Credits

---

hb/index.php
lib/tmjsfuncs.js
user/mapview.php
user/region.php
user/system.php

Enhancement for #179.
A clean merge, despite all @jteresco's more recent work on some of these files. :D
Feature is live on my site mirror (link in the forum), so we can test it out & look for problems before merging.

Intersecting/Concurrent links keep same ctr/zoom

---

lib/tmphpfuncs.php
user/region.php
user/system.php

MySQL 5.7-compatible ranking fix for #328

---

user/region.php
user/system.php

http://forum.travelmapping.net/index.php?topic=2451

stat tables in untraveled regions & systems

---

hb/index.php

Addresses #103.
Also contains the commits in #348. What's new here is 77a161993ad4b3b43e0900e0067fc83ba6d78a7d.
This works on lab2, but I can't be sure it'll work on noreaster. Because MySQL.
Suggest giving it a spin on tmtest & seeing how things work.
**Tested with:**
mb.mb261
me.me069
me.me116
me.me169
ns.ns366
swe.e16

fix for #103

---

credits.php

Please clarify that the links are going to show up on the website.  The lack of hyperlinks (minus the change in the PennDOT VideoLog link) was the main reason that I updated this.

Updating credits

---

user/region.php

for friendlier copy-paste into mysql client

"Statistics by Route" query: '\t' -> ' '

---

hb/index.php

HB lat/lon/zoom comments

---

devel/datacheck.php

See also: https://github.com/TravelMapping/DataProcessing/pull/265

BAD_ANGLE & LABEL_UNDERSCORES always error (Web)

---

devel/manual/wayptlabels.php

wayptlabels.php citation links

---

devel/datacheck.php

datacheck.php: link to HB centered at error

---

devel/datacheck.php

from https://github.com/TravelMapping/Web/issues/5#issuecomment-565734175:
> Thanks to @Thing342's [orClauseBuilder function](https://github.com/TravelMapping/Web/blame/09a176f30c6f80a321eb4017ced27bd6ee7933dc/lib/tmphpfuncs.php#L103-L126), filtering for multiple regions or systems or error codes was easy. The QS parameter support is there on lab2, just not the UI controls, so we've got to manually create our own URLs.
http://205.209.84.174/devel/datacheck.php?rg=me,mb
http://205.209.84.174/devel/datacheck.php?sys=usai,usausb
http://205.209.84.174/devel/datacheck.php?show=HIDDEN_TERMINUS,LABEL_SLASHES
http://205.209.84.174/devel/datacheck.php?hide=VISIBLE_DISTANCE,SHARP_ANGLE

select multiple rg/sys, show/hide by code

---

devel/datacheck.php

see also: https://github.com/TravelMapping/DataProcessing/pull/277

MALFORMED_LAT & MALFORMED_LON always error

---

devel/datacheck.php

Copied @michihdeu's changes to /devel_new/datacheck.php into /devel/datacheck.php & tested on lab2. Looks good.

error colors for /devel/datacheck.php

---

wptedit/wptfunctions.js

https://github.com/TravelMapping/Web/issues/374#issuecomment-644314254

wptedit datacheck error codes sans []

---

devel/datacheck.php
devel_new/datacheck.php

see https://github.com/TravelMapping/DataProcessing/pull/344

display FP codes for LACKS_GENERIC errors

---

devel/datacheck.php
devel/logs.php
devel/manual/maintenance.php
devel/manual/syserr.php
devel/manual/sysnew.php

See also #504 and #505
Broken links are "../../logs" on syserr.php

Link fixes

---

devel/datacheck.php

https://github.com/TravelMapping/Web/issues/403#issuecomment-643684157

datacheck: link error codes to syserr.php

---

wptedit/wptfunctions.js

wptedit: links to syserr.php

---

devel/datacheck.php
devel/manual/syserr.php

* new INTERSTATE_NO_HYPHEN datacheck; see TravelMapping/DataProcessing#350
* syserr.php: describe INTERSTATE_NO_HYPHEN
* datacheck.php: INTERSTATE_NO_HYPHEN is blue
* datacheck.php: DISCONNECTED_ROUTE links to ConnectedRoute view in HB. Closes #549.

INTERSTATE_NO_HYPHEN & DISCONNECTED_ROUTE

---

devel/manual/syserr.php

[proposed](https://github.com/TravelMapping/Web/issues/550) but not yet supported in wptedit

INTERSTATE_NO_HYPHEN color coding

---

devel/datacheck.php
devel/manual/syserr.php
devel/manual/wayptlabels.php
wptedit/wptfunctions.js

The companion pull request in DataProcessing will be along shortly.

US_LETTER datacheck

---

devel/manual/syserr.php
wptedit/wptfunctions.js

Closes #569.
Also contains the commit in #566. I made the quick-n-lazy assumption that was already merged, and FFWDed my local branches.

use current zoom level in external link buttons

---

shields/banner_template.svg

Border colors were not changing for SC, SD, and VT banners.

Fix border colors for SC, SD, and VT banners

---

user/region.php
user/system.php

* Keep rg= arg when clicking on "travsystem" table row
* Make rank numbers in "travregion/travsystem" tables match tm_fetch_user_row_with_rank

"travsystem" table fixes

---

user/region.php
user/system.php

https://github.com/TravelMapping/Web/issues/97#issuecomment-865222245
Also moves the
checkbox to take up less vertical space at the top of the page.
---
Live on lab2.

region.php & system.php UI elements

---

devel/manual/syserr.php

https://forum.travelmapping.net/index.php?topic=2095.msg25905#msg25905

clarify causes of ABBREV_AS_CON_BANNER

---

devel/datacheck.php

See https://github.com/TravelMapping/DataProcessing/pull/478

ABBREV_AS_CON_BANNER info for both csv line numbers

---

devel/manual/wayptlabels.php

https://forum.travelmapping.net/index.php?topic=4644

wayptlabels: keepletter

---

devel/manual/includepts.php

https://forum.travelmapping.net/index.php?topic=4555

includepts: tolerance lines

---

devel/datacheck.php
devel/manual/syserr.php

See https://github.com/TravelMapping/DataProcessing/pull/480

ABBREV_NO_CITY (Web)

---

devel/logs.php

list flippedroutes.log on logs.php, last category

---

shields/shieldgen.php

Add a case for the jpnh system

---

shields/shieldgen.php
shields/template_jpne.svg
shields/template_jpnh.svg

Added viewbox to jpnh, attempting to solve image scaling problems

Added shield support for jpne

---

devel/datacheck.php
devel/manual/syserr.php
wptedit/wptfunctions.js

see https://github.com/TravelMapping/DataProcessing/pull/547

LABEL_LOWERCASE & LOWERCASE_SUFFIX (Web)

---

wptedit/wptfunctions.js

VISIBLE_DISTANCE fix for HIDDEN_TERMINUS cases

---

wptedit/wptfunctions.js

https://github.com/TravelMapping/Web/pull/751#issuecomment-1485452783

right parenthesis fix for #751

---

user/mapview.php

@jteresco I don't know if there is a temporary copy of the source code for railways? If so, please apply the change. In the end of the day, we don't need to distinguish since System colors is good enough for any kind of transportation mode.

Highway System Colors -> System Colors

---

devel/logs.php

See https://github.com/TravelMapping/DataProcessing/pull/607

highwaydatastats.log -> routedatastats.log

---

devel/manual/syshwylist.php

https://github.com/TravelMapping/DataProcessing/pull/639

manual: cross-region AltRouteNames

---

devel/manual/syserr.php

Related: https://github.com/TravelMapping/DataProcessing#641
This PR doesn't require that PR, but if merging that one, merging this one too is a good idea.

LABEL_INVALID_CHAR & MALFORMED_URL clarification

---

devel/manual/syserr.php

See also https://github.com/TravelMapping/DataProcessing/pull/651

MULTI_REGION_OVERLAP

---

credits.php

Update credits for DEU

---

shields/shieldgen.php
shields/template_hkrt.svg

* Create template_hkrt.svg
* Update shieldgen.php

Adding Hong Kong Route shield

---

shields/shield_nj.atlbricon.svg

Add shield for NJ AtlBriCon

---

shields/shieldgen.php

Fixing yet another typo in the same line of code...

Another typo fix

---

shields/shield_ausnsw.bmd.svg
shields/shield_ausvic.n001altmel.svg
shields/shield_auswa.n094altkal.svg
shields/shieldgen.php
shields/template_uryrn.svg
shields/template_uryrn_wide.svg

Batch 18 Fixes
